export const FETCH_ADD_SUCCESS       = "FETCH_ADD_SUCCESS";
export const FETCH_EDIT_SUCCESS      = "FETCH_EDIT_SUCCESS";
export const FETCH_DELETE_SUCCESS    = "FETCH_DELETE_SUCCESS";
export const FETCH_GET_SUCCESS       = "FETCH_GET_SUCCESS";
export const FETCH_ADD_TO_CART       = "FETCH_ADD_TO_CART";
export const FETCH_DELETE_AT_CART    = "FETCH_DELETE_AT_CART";
export const FETCH_GET_CART_PRODUCTS = "FETCH_GET_CART_PRODUCTS";